[general]
id = "cs1-ff00_0_112-1"
config_dir = "gen/ASff00_0_112"
reconnect_to_dispatcher = true

[trust_db]
connection = "gen-cache/cs1-ff00_0_112-1.trust.db"

[beacon_db]
connection = "gen-cache/cs1-ff00_0_112-1.beacon.db"

[path_db]
connection = "gen-cache/cs1-ff00_0_112-1.path.db"

[tracing]
enabled = true
debug = true
agent = "0.0.0.0:6831"

[metrics]
prometheus = "127.0.0.27:30452"

[features]

[log.console]
level = "debug"

[drkey]
epoch_duration = "1m"
cert_file = "gen/ASff00_0_112/crypto/as/ISD1-ASff00_0_112.pem"
key_file = "gen/ASff00_0_112/crypto/as/cp-as.key"
[drkey.drkey_db]
connection = "gen-cache/cs1-ff00_0_112-1.drkey.db"
[drkey.delegation]
# these are the endhosts allowed to get DSs, grouped by protocol
piskes = ["127.0.0.1"]
